spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_data?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true


server:
  port: 8010

cors:
  allowed-origins: http://localhost:5173,https://yourdomain.com

