spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_data
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8010

# CORS 설정은 WebConfig.java에서 처리합니다.
