server:
  port: 8010
  servlet:
    context-path: /
    encoding:
      charset: utf-8




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_data  # 데이터베이스 URL
    username: root  # 데이터베이스 사용자 이름
    password: 1234  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate Dialect (MySQL 8의 경우)
        ddl-auto: update  # 스키마 자동 업데이트 옵션
    show-sql: true  # SQL 쿼리를 로그에 출력합니다

  hikari:
    maximum-pool-size: 10  # 최대 커넥션 수
    minimum-idle: 5  # 최소 유휴 커넥션 수
    idle-timeout: 30000  # 유휴 커넥션 타임아웃 (밀리초 단위)
    max-lifetime: 1800000  # 커넥션 최대 수명 (밀리초 단위)
    connection-timeout: 30000  # 커넥션 타임아웃 (밀리초 단위)
  banner:
    mode: off  # 배너 비활성화
management:
  endpoints:
    web:
      exposure:
        include: health, info

#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
